# Generated by Django 5.0 on 2025-10-28 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(choices=[('courier', "Кур'єр"), ('express', 'Експрес'), ('pickup', 'Самовивіз')], max_length=20, verbose_name='Спосіб доставки')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('preparing', 'Готується'), ('on_way', 'В дорозі'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('delivery_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вартість доставки')),
                ('estimated_time', models.CharField(blank=True, max_length=100, verbose_name='Орієнтовний час')),
                ('delivery_details', models.JSONField(blank=True, null=True, verbose_name='Деталі доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата доставки')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('payment_method', models.CharField(choices=[('card', 'Банківська картка'), ('cash', 'Готівка'), ('online', 'Онлайн оплата')], max_length=20, verbose_name='Спосіб оплати')),
                ('status', models.CharField(choices=[('pending', 'Очікує оплати'), ('processing', 'Обробляється'), ('completed', 'Завершено'), ('failed', 'Помилка'), ('refunded', 'Повернено')], default='pending', max_length=20, verbose_name='Статус')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID транзакції')),
                ('payment_details', models.JSONField(blank=True, null=True, verbose_name='Деталі платежу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплати')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Платіж',
                'verbose_name_plural': 'Платежі',
                'ordering': ['-created_at'],
            },
        ),
    ]
