# Generated by Django 5.0 on 2025-10-28 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('address', models.CharField(max_length=300, verbose_name='Адреса')),
                ('city', models.CharField(default='Львів', max_length=100, verbose_name='Місто')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('working_hours', models.CharField(default='9:00-21:00', max_length=100, verbose_name='Графік роботи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Довгота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
            ],
            options={
                'verbose_name': 'Аптека',
                'verbose_name_plural': 'Аптеки',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кількість')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Останнє оновлення')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_stocks', to='medications.medication', verbose_name='Медикамент')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='pharmacies.pharmacy', verbose_name='Аптека')),
            ],
            options={
                'verbose_name': 'Залишок в аптеці',
                'verbose_name_plural': 'Залишки в аптеках',
                'unique_together': {('pharmacy', 'medication')},
            },
        ),
    ]
