# Generated by Django 5.0 on 2025-10-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_created', 'Замовлення створено'), ('order_confirmed', 'Замовлення підтверджено'), ('order_ready', 'Замовлення готове'), ('order_delivered', 'Замовлення доставлено'), ('order_cancelled', 'Замовлення скасовано'), ('promotion', 'Акція'), ('bonus_added', 'Нараховано бонуси'), ('medication_available', 'Препарат в наявності'), ('info', 'Інформація')], max_length=30, verbose_name='Тип сповіщення')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], max_length=10, verbose_name='Канал')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Надіслано')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('sent_at', models.DateTimeField(auto_now=True, verbose_name='Дата відправки')),
            ],
            options={
                'verbose_name': 'Сповіщення',
                'verbose_name_plural': 'Сповіщення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_created', 'Замовлення створено'), ('order_confirmed', 'Замовлення підтверджено'), ('order_ready', 'Замовлення готове'), ('order_delivered', 'Замовлення доставлено'), ('order_cancelled', 'Замовлення скасовано'), ('promotion', 'Акція'), ('bonus_added', 'Нараховано бонуси'), ('medication_available', 'Препарат в наявності'), ('info', 'Інформація')], max_length=30, unique=True, verbose_name='Тип сповіщення')),
                ('email_subject', models.CharField(blank=True, max_length=200, verbose_name='Тема email')),
                ('email_template', models.TextField(blank=True, help_text='Використовуйте {user_name}, {order_id}, {total_price} для підстановки', verbose_name='Шаблон email')),
                ('sms_template', models.CharField(blank=True, help_text='Максимум 160 символів', max_length=160, verbose_name='Шаблон SMS')),
                ('push_template', models.CharField(blank=True, max_length=200, verbose_name='Шаблон Push')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Шаблон сповіщення',
                'verbose_name_plural': 'Шаблони сповіщень',
            },
        ),
    ]
