# Generated by Django 5.0 on 2025-10-28 21:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('manufacturer', models.CharField(max_length=200, verbose_name='Виробник')),
                ('category', models.CharField(choices=[('analgesic', 'Знеболююче'), ('antibiotic', 'Антибіотик'), ('vitamin', 'Вітаміни'), ('antiseptic', 'Антисептик'), ('cardiovascular', 'Серцево-судинні'), ('gastrointestinal', 'Шлунково-кишкові'), ('dermatological', 'Дерматологічні'), ('other', 'Інше')], max_length=50, verbose_name='Категорія')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ціна')),
                ('is_prescription', models.BooleanField(default=False, verbose_name='Рецептурний')),
                ('active_ingredient', models.CharField(blank=True, max_length=200, verbose_name='Діюча речовина')),
                ('dosage', models.CharField(blank=True, max_length=100, verbose_name='Дозування')),
                ('image', models.ImageField(blank=True, null=True, upload_to='medications/', verbose_name='Зображення')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Медикамент',
                'verbose_name_plural': 'Медикаменти',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='medications_name_0c05c3_idx'), models.Index(fields=['category'], name='medications_categor_d82bd0_idx'), models.Index(fields=['is_prescription'], name='medications_is_pres_a01e1d_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Оцінка (1-5)')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата відгуку')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='medications.medication', verbose_name='Медикамент')),
            ],
            options={
                'verbose_name': 'Відгук про медикамент',
                'verbose_name_plural': 'Відгуки про медикаменти',
                'ordering': ['-created_at'],
            },
        ),
    ]
