# Generated by Django 5.0 on 2025-10-28 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterUniqueTogether(
            name='medicationreview',
            unique_together={('medication', 'user')},
        ),
    ]
